language: c
compiler: gcc
sudo: false
dist: trusty
osx_image: xcode8

branches:
  only:
    - master
    - travis
os:
  - linux
  - osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - deadsnakes
    packages: [autoconf, automake, autotools-dev, bzip2, gcc-4.9, libtool,
      libjpeg-dev, libtiff4-dev, libpng12-dev, libfreetype6-dev, libgif-dev,
      libx11-dev, libxml2-dev, libpango1.0-dev, libcairo2-dev, python3.5-dev]

cache:
  directories:
    - $TRAVIS_BUILD_DIR/travisdeps

before_install:
  - set -e
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update || brew update; fi

install:
  - |
    export DEPSPREFIX=$TRAVIS_BUILD_DIR/travisdeps

    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      export PREFIX=$TRAVIS_BUILD_DIR/target
      export FTVER=`dpkg -s libfreetype6-dev | perl -ne 'print $1 if /^Version: (\d+(?:\.\d+)+)/'`
      export SFFTVER=`echo $FTVER | perl -ne 'print $1 if /^(\d+(?:\.\d+){1,2})/'`
      export PATH=$PATH:$DEPSPREFIX/bin:$PREFIX/bin
      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DEPSPREFIX/lib:$PREFIX/lib
      export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$DEPSPREFIX/lib/pkgconfig
      export CC=gcc-4.9

      # This block only runs if the cache isn't present.
      if [ ! "$(ls -A $DEPSPREFIX)" ]; then
        mkdir -p work && pushd work
        wget 'https://github.com/zeromq/zeromq4-1/releases/download/v4.1.5/zeromq-4.1.5.tar.gz' -O - |tar -zxf -
        wget 'https://github.com/zeromq/czmq/releases/download/v3.0.2/czmq-3.0.2.tar.gz' -O - |tar -zxf -
        wget 'https://github.com/fontforge/libspiro/releases/download/0.5.20150702/libspiro-0.5.20150702.tar.gz' -O - | tar -zxf -
        wget 'https://github.com/fontforge/libuninameslist/releases/download/20160701/libuninameslist-20160701.tar.gz' -O - | tar -zxf -
        wget 'https://bitbucket.org/sortsmill/libunicodenames/downloads/libunicodenames-1.1.0_beta1.tar.xz' -O - | tar -Jxf -
        wget --tries 1 "http://download.savannah.gnu.org/releases/freetype/freetype-$FTVER.tar.gz" || \
          wget "https://sourceforge.net/projects/freetype/files/freetype2/$SFFTVER/freetype-$FTVER.tar.gz"

        pushd zeromq-4.1.5 && ./configure --prefix=$DEPSPREFIX && make -j4 && make install && popd
        pushd czmq-3.0.2 && ./configure --prefix=$DEPSPREFIX && make -j4 && make install && popd
        pushd libspiro-0.5.20150702 && ./configure --prefix=$DEPSPREFIX && make -j4 && make install && popd
        pushd libuninameslist-20160701 && ./configure --prefix=$DEPSPREFIX && make -j4 && make install && popd
        pushd libunicodenames-1.1.0_beta1 && ./configure --prefix=$DEPSPREFIX && make -j4 && make install && popd
        tar -zxf freetype-$FTVER.tar.gz -C $DEPSPREFIX
        popd
      fi
    else
      # Disable fc-cache on fontconfig install. Because it's slow.
      sed -i.bak '/fc-cache/d' "$(brew --prefix)/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/fontconfig.rb"
      # Install cairo and pango, using cached bottles if possible
      pushd $DEPSPREFIX
      brew install *cairo*bottle* || (brew install --build-bottle cairo --with-x11 && brew bottle cairo)
      brew install *pango*bottle* || (brew install --build-bottle pango --with-x11 && brew bottle pango)
      brew outdated | grep -q cairo && rm *cairo*bottle* || true
      brew outdated | grep -q pango && rm *pango*bottle* || true
      popd
      brew install ./travis-scripts/fontforge.rb --HEAD --with-x11 --only-dependencies
    fi

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      export PYTHON=python3.5
      export PYTHONPATH=$PYTHONPATH:$PREFIX/lib/python$($PYTHON -c "import sys; print('{0}.{1}'.format(sys.version_info.major, sys.version_info.minor))")/site-packages
      export FTSRC=--with-freetype-source=$DEPSPREFIX/freetype-$FTVER
      export FFPREFIX=--prefix=$PREFIX
      export CFLAGS="-fdiagnostics-color=auto -Wall -Wno-switch"
      #Why.
      export LIBSPIRO_CFLAGS=`pkg-config --cflags libspiro` && export LIBSPIRO_LIBS=`pkg-config --libs libspiro`
      export LIBUNINAMESLIST_CFLAGS=`pkg-config --cflags libuninameslist` && export LIBUNINAMESLIST_LIBS=`pkg-config --libs libuninameslist`
    else
      export PYTHON=python
      export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig
      export MSGFMT=/usr/local/opt/gettext/bin/msgfmt
    fi
  - ./bootstrap
  - ./configure $FFPREFIX $FTSRC
  - make -j4
  - make install
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make distcheck; fi
  - fontforge -version
  - $PYTHON -c "import fontforge; import psMat; print(fontforge.__version__, fontforge.version())"
  # This is needed, otherwise the OS X build errors out...
  - set +e
